<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="com.mobian.model.TljzGoods" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<script type="text/javascript">
	$(function() {
		parent.$.messager.progress('close');		
	});
</script>
<div class="easyui-layout" data-options="fit:true,border:false">
	<div data-options="region:'center',border:false">
		<table class="table table-hover table-condensed">
				<tr>	
					<th><%=TljzGoods.ALIAS_ADDTIME%></th>	
					<td>
						${ljzGoods.addtime}							
					</td>							
					<th><%=TljzGoods.ALIAS_UPDATETIME%></th>	
					<td>
						${ljzGoods.updatetime}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TljzGoods.ALIAS_ISDELETED%></th>	
					<td>
						${ljzGoods.isdeleted}							
					</td>							
					<th><%=TljzGoods.ALIAS_SHOP_ID%></th>	
					<td>
						${ljzGoods.shopId}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TljzGoods.ALIAS_TITLE%></th>	
					<td>
						${ljzGoods.title}							
					</td>							
					<th><%=TljzGoods.ALIAS_PRICE%></th>	
					<td>
						${ljzGoods.price}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TljzGoods.ALIAS_ICON%></th>	
					<td>
						${ljzGoods.icon}							
					</td>							
					<th><%=TljzGoods.ALIAS_IMAGE_URL%></th>	
					<td>
						${ljzGoods.imageUrl}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TljzGoods.ALIAS_DESCRIBTION%></th>	
					<td>
						${ljzGoods.describtion}							
					</td>							
					<th><%=TljzGoods.ALIAS_IS_PUT_AWAY%></th>	
					<td>
						${ljzGoods.isPutAway}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TljzGoods.ALIAS_LIMIT_NUMBER%></th>	
					<td>
						${ljzGoods.limitNumber}							
					</td>							
					<th><%=TljzGoods.ALIAS_FREIGHT%></th>	
					<td>
						${ljzGoods.freight}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TljzGoods.ALIAS_SHARE_AMOUNT%></th>	
					<td>
						${ljzGoods.shareAmount}							
					</td>							
					<th><%=TljzGoods.ALIAS_PRIZE_PRE%></th>	
					<td>
						${ljzGoods.prizePre}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TljzGoods.ALIAS_PRIZE_AMOUNT%></th>	
					<td>
						${ljzGoods.prizeAmount}							
					</td>							
					<th><%=TljzGoods.ALIAS_PRIZE_NUMBER%></th>	
					<td>
						${ljzGoods.prizeNumber}							
					</td>							
				</tr>		
		</table>
	</div>
</div>